### ISSUE TITLE
A command not working

### ISSUE THREAD

**Issue by MrKriim** [Code-Society-Lab/grace#108]
**Describe the bug**

**Have you been able to reproduce the bug?**

**Screenshots**

[
![IMG_3711](https://github.com/Code-Society-Lab/grace/assets/101586794/6b0f32fc-3913-4dc7-94fb-ca7e3aa36eed)
](url)
**Desktop (please complete the following information):**

**Additional context** 

![IMG_3711](https://github.com/Code-Society-Lab/grace/assets/101586794/a9eef3aa-169d-40d5-a580-d28e1618adf4)

**Comment by PenguinBoi12** [comment]
Hey @MrKriim, thanks for reporting this. This is not a bug exactly. The bison quote API that we used is currently under some maintenance by @SoyBison. We're waiting until it gets back online or finally deprecated. 

Thanks again!

**Comment by PenguinBoi12** [comment]
Bisonquote will be removed https://github.com/Code-Society-Lab/grace/issues/113
