### ISSUE TITLE
Goosed Command

### ISSUE THREAD

**Issue by ConfusedGoose** [Code-Society-Lab/grace#27]
we need the command ::Goosed.
This command will have the bot respond with Get Goosed and a random Gif of geese attacking
Example of gifs like:
https://tenor.com/view/goose-gif-5452772
https://tenor.com/view/birds-kid-nope-run-attack-gif-11840434
https://tenor.com/view/bird-attack-inside-car-goose-wtf-horror-gif-19141111

**Comment by MrNesli** [comment]
Hi, I can work on this one!

**Comment by chrisdedman** [comment]
I assigned the issue to you @MrNesli thank you
