### ISSUE TITLE
More managed cogs

### ISSUE THREAD

**Issue by rachit1601** [Code-Society-Lab/grace#30]
**Is your feature request related to a problem? Please describe.**
The help menu & cogs are a little unorganised 

**Describe the solution you'd like**
Like ping command should be inside grace cogs

**Comment by PenguinBoi12** [comment]
> **Is your feature request related to a problem? Please describe.**
> The help menu & cogs are a little unorganised 
> 
> **Describe the solution you'd like**
> Like ping command should be inside grace cogs
> 
> 
> 

Indeed there is a small restructuration that has to be done and that will be done soon with the extensions configurations. Thanks for your input.
