### ISSUE TITLE
Please make an Bookmarker bot so that anyone can get the message they want to save, straight to personal chats. 

### ISSUE THREAD

**Issue by dgdogg** [Code-Society-Lab/grace#32]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when [I need to save some messages and it gets lost in the messages going on]

**Describe the solution you'd like**
Using a bookmark emoji like this, 📖 or 📕 we can get the message personally messaged to us by a bot.

**Comment by PenguinBoi12** [comment]
The issue is temporarily locked because this issue needs a database implementation first, which is currently in development.
