### ISSUE TITLE
Add a praise behavior to Grace

### ISSUE THREAD

**Issue by PenguinBoi12** [Code-Society-Lab/grace#38]
It would be interesting to add an encouragement/praise behavior to Grace. In other words, if we praise or encourage Grace, she would react with 😊 and if you do the opposite it would react 😠.

**Comment by chrisdedman** [comment]
Isn't this feature already implemented to Grace?

**Comment by PenguinBoi12** [comment]
> Member

Kind of but not exactly. We have something similar but this issue is to improve the feature we already have.
