### ISSUE TITLE
Censor functionality

### ISSUE THREAD

**Issue by PenguinBoi12** [Code-Society-Lab/grace#42]
Not everyone is able to respect the firsts rules. Thus, we need to add a censoring functionality to Grace. The bot would erase the message or change the blacklisted word's characters by stars (*) or anything that would hide the words.

We might want to log the messages in any cases (if they are modified or deleted) and show clearly what words have been censored. We need to be able to change the channel in which the logs will be sent and be able to list, add and remove blacklisted word.

**Comment by SoyBison** [comment]
Censor  bot is back online so this is lower priority now, but still would be nice :)

**Comment by PenguinBoi12** [comment]
Not relevant anymore. Discord released their own censoring feature.
