### ISSUE TITLE
Codle

### ISSUE THREAD

**Issue by PenguinBoi12** [Code-Society-Lab/grace#45]
To increase user participation to the server, it could be interesting to do weekly code challenges. They could win prizes like xp, roles and more.

We would be able to see the current challenge and perhaps past ones, send our solution so the bot can execute and check if all given tests passes. Upon completion, the price would be given and the user scoreboard shown.

We need a way to easily add questions (we need a start and end date) reserved only for the admins or user with the given role.

The member must be able to use multiple languages. (For ex. Python, Java, C, C++, JavaScript, etc)

**Note**
If an existing API is found that does pretty much what we're looking for, it could faster and easier to use it instead.

**Comment by MrNesli** [comment]
Wanna try this one, but check the Voting PR pls

**Comment by PenguinBoi12** [comment]
This require to much development.
