### ISSUE TITLE
Point system for help

### ISSUE THREAD

**Issue by ghost** [Code-Society-Lab/grace#46]
# Thanking feature

**What**
- Giving user points if they are "thanked" by someone (for helping with some problem or explaining some concept or whatever 

**Why**
- number of "thanks" can be an indicator of a person's knowledge/experience/ value
- if a person is thanked alot, it means they helped alot of people
- thanks ranking & leaderboard could be used for clout / reputation

**How**
- maybe trigger the "thanking" function by a command or writing a message in the form of "thanks @xyz"
- "thank" points could be stored with username in sqlite or something simple

**Comment by MrNesli** [comment]
Will be working on it
