### ISSUE TITLE
Poll Cog timer issue.

### ISSUE THREAD

**Issue by chrisdedman** [Code-Society-Lab/grace#91]
**Describe the bug**
Issue with the poll timer. The timer froze after a couple of minutes. Tested with a 3600 second (1h) timer and froze after 12 minutes.

**Screenshots**

![681B6535-3050-4C8D-A5EA-E9CADDD3A721](https://user-images.githubusercontent.com/61106361/213599215-d26ef25e-928d-4d89-8831-15432312c175.jpeg)

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
Additionally, like shown in the screenshot, when the user want to change its answer, the interaction fail (could be only because of the timer issue, I’ve been able to change my answer a couple of second (a minute?) after my first answer, but not once the timer froze.).

**Comment by DIYDude69** [comment]
What could be a probable method for fixing this particular bug in grace? What has been tried? Asking to "get to the bottom of" this particular bug or perhaps start a conversation to begin looking into this issue.

**Comment by PenguinBoi12** [comment]
> What could be a probable method for fixing this particular bug in grace? What has been tried? Asking to "get to the bottom of" this particular bug or perhaps start a conversation to begin looking into this issue.

Thank you for taking interest into this feature will be deprecated with the arrival of Polls on discord. I just saw they are released now on the server so I'm going to close this issue and create another for the removal of the polls. 

Sorry.

**Comment by DIYDude69** [comment]
> > What could be a probable method for fixing this particular bug in grace? What has been tried? Asking to "get to the bottom of" this particular bug or perhaps start a conversation to begin looking into this issue.
> 
> Thank you for taking interest into this feature will be deprecated with the arrival of Polls on discord. I just saw they are released now on the server so I'm going to close this issue and create another for the removal of the polls.
> 
> Sorry.

Hey, no problem. Didn't know that this was gonna get deprecated, but whatever. It is what it is.
