### ISSUE TITLE
Change pun feature

### ISSUE THREAD

**Issue by Gangsta-Muffin** [Code-Society-Lab/grace#97]
**Describe the feature**

So this feature is less of a feature, but more a change to a feature:

I suggest that the world puns (provided by grace) get limited channels. 

What channels am I referring to specifically:
Well, for one, I do not find it appropriate, that grace provides puns in help threads. Therefore, I would suggest that grace recievs checks to stop sending puns into help threads. This of course would also go for challenge threads, as well as other channels such as (perhaps) the moderate channels, bot commands channel and perhaps even server suggestions channel (this one perhaps a bit more lenient)

Why am I suggesting this feature?:
While it is a fun little feature, it can and does cause for unnecessary messages in channels where it would be unwanted, as the initial message (of course) comes from Grace (ie. the pun itself), and then can cause for further unnecessary messages, if newcomers are unaware of the feature, and start to reflect on the experience (image provides perfect demonstration of this happening)

**Additional context** 
 
![image](https://user-images.githubusercontent.com/94480512/222248317-caf43aa8-2c1c-41b2-9127-d44e8e4e694f.png)

[Help Thread from the Image](https://discord.com/channels/823178343943897088/1080564582080327803/1080564587499364404)

**Comment by PenguinBoi12** [comment]
This has been addressed. Now, puns are rate limited so they won't spam channels each time one of the trigger is sent. Pull Request implementing the cooldown #100
